spring:
  config:
    import: optional:file:.env[.properties]
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true

app:
  frontend-origin: ${FRONTEND_ORIGIN:http://localhost:3000}
